enum PostActionType {
  CREATE = "CREATE",
  FETCH_ALL = "FETCH_ALL",
  FETCH_ONE = "FETCH_ONE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LIKE = "LIKE",
  SEARCH = "SEARCH",
  CREATE_COMMENT = "COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  START_LOADING = "START_LOADING",
  END_LOADING = "END_LOADING",
}

export default PostActionType;
